apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: pluto
volumes:
  - volume: /media/kubernetes/data:/kubernetes
    nodeFilters:
      - server:0
      - agent:*
  - volume: /media/kubernetes/pvc:/var/lib/rancher/k3s/storage
    nodeFilters:
      - all
ports:
  - port: 12345:80 # does not redirect to https
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer
  - port: 25575:25575/udp
    nodeFilters:
      - loadbalancer
